trigger:
- main

resources:
  repositories:
    - repository: mygithubrepo
      type: github
      name: kinjatoro/react-native-prueba
      endpoint: pipeline3 # Nombre de la conexión de servicio

pool:
  name: Default # Nombre del pool de agentes auto-hospedados

steps:
- checkout: mygithubrepo # Usar el nombre del repositorio definido en `resources`

- script: |
    echo "Hello, World!"
  displayName: 'Run a one-line script'


