trigger:
- main

pool:
  name: Default # Usa el nombre correcto de tu pool de agentes auto-hospedados

steps:
- checkout: self
  name: CheckoutGitHub
  endpoint: pipeline3 # Nombre de la conexión de servicio para GitHub

- script: |
    echo "Hello, World!"
  displayName: 'Run a one-line script'

